version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user # cambiarlo por el usuario deseado
      RABBITMQ_DEFAULT_PASS: password # cambiarlo por la contraseña deseada 